import usersRouter from './users.routes.js';
import productRouter from './product.route.js';
import categoryRouter from './category.routes.js';
import subcategoryRouter from './subcategory.routes.js';
import brandRouter from './brand.routes.js';
import reviewRouter from './review.routes.js';
import wishlistRouter from './wishlist.routes.js';
import addressRouter from './address.routes.js';
import couponRouter from './coupon.routes.js';
import cartRouter from './cart.routes.js';
import orderRouter from './order.routes.js';
import chatRouter from './chat.routes.js';
const mountRoutes = (app) => {
  app.use('/api/users', usersRouter);
  app.use('/api/products', productRouter);
  app.use('/api/categories', categoryRouter);
  app.use('/api/subcategories', subcategoryRouter);
  app.use('/api/brands', brandRouter);
  app.use('/api/reviews', reviewRouter);
  app.use('/api/wishlist', wishlistRouter);
  app.use('/api/address', addressRouter);
  app.use('/api/coupons', couponRouter);
  app.use('/api/cart', cartRouter);
  app.use('/api/orders', orderRouter);
  app.use('/api/chat', chatRouter);
};
export default mountRoutes;
